version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: build
          command: cd WebAppForDocker && docker build .
      - run:
          name: Print the Current Time
          command: date