version: 2

defaults: &defaults
  docker:
    - image: circleci/openjdk:11-node-browsers

jobs:
  build:
    <<: *defaults

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: docker Build
          command: cd WebAppForDocker && docker build .
      - run:
          name: Print the Current Time
          command: date
  test:
    <<: *defaults
    steps:
    - checkout
      - run:
          name: testing
          command: pwd && ./test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

